builds:
  - binary: eli
    main: ./cmd/eli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7

    env:
      - CGO_ENABLED=0

  - binary: eliotd
    main: ./cmd/eliotd
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7

    env:
      - CGO_ENABLED=0

archive:
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brew:
  name: eli
  github:
    owner: ernoaapa
    name: homebrew-eliot
  homepage: "http://eliot.run"
  description: "Container management system for IoT devices"
  test: |
    system "#{bin}/eli --version"

dockers:
  - binary: eli
    goos: linux
    goarch: amd64
    image: ernoaapa/eli
    dockerfile: Dockerfile.eli
    tag_templates:
      - "v{{ .Version }}"

  - binary: eliotd
    goos: linux
    goarch: amd64
    image: ernoaapa/eliotd
    dockerfile: Dockerfile.eliotd
    tag_templates:
      - "v{{ .Version }}-amd64"

  - binary: eliotd
    goos: linux
    goarch: arm64
    image: ernoaapa/eliotd
    dockerfile: Dockerfile.eliotd
    tag_templates:
      - "v{{ .Version }}-arm64"

nfpm:
  homepage: http://www.eliot.run
  maintainer: Erno Aapa <erno.aapa@gmail.com>
  description: "Container management system for IoT devices"
  license: Apache 2.0
  formats:
    - deb

  # At the moment repositories includes really old version of containerd
  # so we bake in the containerd daemon and runc binary
  # dependencies:
  #   - containerd@v1.0.3
  dependencies:
    - libseccomp2 #(Actually runc dep)

  files:
    "build/etc/systemd/system/eliotd.service": "/etc/systemd/system/eliotd.service"
    "build/etc/systemd/system/containerd.service": "/etc/systemd/system/containerd.service"
    # Built during the build process
    "bin/runc": "/usr/local/bin/runc"
    "bin/containerd": "/usr/local/bin/containerd"
