defaults: &defaults
  docker:
    - image: circleci/golang:1.10
  working_directory: /go/src/github.com/ernoaapa/eliot

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      
      - run: "! go fmt -l pkg cmd 2>&1 | read"
      - run: go vet ./...
      
      # Run tests with overalls to generate also coverage report
      - run: go get github.com/go-playground/overalls
      - run: overalls -project=github.com/ernoaapa/eliot -covermode=atomic -- -race -v
      # Send reports to codecov
      - run: |
          mv overalls.coverprofile coverage.txt
          bash <(curl -s https://codecov.io/bash)

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - run: go get github.com/goreleaser/goreleaser
      - run: goreleaser --snapshot

  publish:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Login Docker hub
          command: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin

      - run: 
          name: Install tools
          command: |
            go get github.com/goreleaser/goreleaser
            go get github.com/estesp/manifest-tool
      - run: goreleaser
      - run: .circleci/scripts/push-docker-manifest.sh $(git describe --tags --always --dirty)

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore: /gh-pages/
            tags:
              only: /.*/
              
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/

      - publish:
          requires:
            - test
            - build
          
          # Don't run when branches updates, only when tags get created
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /v.*/