defaults: &defaults
  docker:
    - image: circleci/golang:1.9
  working_directory: /go/src/github.com/ernoaapa/eliot

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - run: "! go fmt -l pkg cmd 2>&1 | read"
      - run: go vet ./...
      - run: go test -v ./...

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - run: go get github.com/goreleaser/goreleaser
      - run: goreleaser --snapshot --skip-publish

  publish:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - run: go get github.com/goreleaser/goreleaser
      - run: goreleaser

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore: /gh-pages/
            tags:
              only: /.*/
              
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/

      - publish:
          requires:
            - test
            - build
          
          # Don't run when branches updates, only when tags get created
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /v.*/