kernel:
  image: linuxkit/kernel:4.9.50
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:851e9c3ad0574d640b733b92fdb26c368d2f7f8f
  - linuxkit/runc:a1b564248a0d0b118c11e61db9f84ecf41dd2d2a
  - linuxkit/containerd:06876ceef325e49e9ba119659357768d5df89075
  - linuxkit/ca-certificates:e44b0a66df5a102c0e220f0066b0d904710dcb10
onboot:
  - name: sysctl
    image: linuxkit/sysctl:154913b72c6f1f33eb408609fca9963628e8c051
  - name: rngd1
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
    command: ["/sbin/rngd", "-1"]
services:
  - name: getty
    image: linuxkit/getty:797cb79e0a229fcd16ebf44a0da74bcec03968ec
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
  - name: dhcpcd
    image: linuxkit/dhcpcd:f3f5413abb78fae9020e35bd4788fa93df4530b7
  - name: sshd
    image: linuxkit/sshd:505a985d7bd7a90f15eca9cb4dc6ec92789d51a0
    capabilities:
      - all
    binds:
      - /usr/bin/ctr:/usr/bin/ctr # ctr for debugging
      - /containers:/containers # ctr requires access to be able to manage containers
      - /run/containerd:/run/containerd # need access to sockets
  - name: cand
    image: ernoaapa/cand-amd64:63f2878
    command: ["/cand", "--debug", "--labels", "foo=bar", "--manifest", "http://192.168.1.102:3000/api/devices/localtest/manifest"]
    capabilities:
      - all
    binds:
      - /containers:/containers
      - /run/containerd:/run/containerd
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/machine-id:/etc/machine-id
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - path: /etc/machine-id
    contents: "104CECBC-6037-5FCF-AF75-80EB7040CD11"
    mode: "0600"
trust:
  org:
    - linuxkit
