kernel:
  image: linuxkit/kernel:4.9.50
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:7804129bd06218b72c298139a25698a748d253c6
  - linuxkit/runc:a1b564248a0d0b118c11e61db9f84ecf41dd2d2a
  - linuxkit/containerd:417f83f7b8dc1fa36acf90effe44f99c7397480a
  - linuxkit/ca-certificates:e44b0a66df5a102c0e220f0066b0d904710dcb10
  # For development, run in host as init process
  - linuxkit/getty:bf6872ce0a9f3ab519b3e502cc41ba3958bda2a6
onboot:
  - name: sysctl
    image: linuxkit/sysctl:154913b72c6f1f33eb408609fca9963628e8c051
  - name: rngd1
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
    command: ["/sbin/rngd", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
  - name: dhcpcd
    image: linuxkit/dhcpcd:d4408777ed6b6e6e562a5d4938fd09804324b33e
  - name: sshd
    image: linuxkit/sshd:d313eea3d9d7fbcbc927d06a6700325725db2a82
    capabilities:
      - all
    binds:
      - /root/.ssh:/root/.ssh
      - /etc/resolv.conf:/etc/resolv.conf
      - /usr/bin/runc:/usr/bin/runc
      - /usr/bin/ctr:/usr/bin/ctr # ctr for debugging
      - /containers:/containers # ctr requires access to be able to manage containers
      - /var/lib/volumes:/volumes # The directory for pod volumes
      - /run/containerd:/run/containerd # need access to sockets
      - /var/log:/var/log # To be able to run 'ctr t attach' to view logs
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock
      - /tmp:/tmp
  - name: cand
    image: ernoaapa/cand-amd64:b829d9d
    command: ["/cand", "--debug", "--labels", "camera=true,name=first", "--manifest", "http://can.ngrok.io/api/devices/first/manifest", "--report", "http://can.ngrok.io/api/devices/first/pods"]
    capabilities:
      - all
    binds:
      - /containers:/containers
      - /run/containerd:/run/containerd
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/machine-id:/etc/machine-id
  - name: can-api
    image: ernoaapa/can-api-amd64:f9e96e7-dirty
    command: ["/can-api", "--debug", "--listen", "0.0.0.0:5000"]
    capabilities:
      - all
    net: host
    runtime:
      mkdir: ["/var/lib/volumes"]
    binds:
      - /containers:/containers
      - /var/lib/volumes:/volumes
      - /run/containerd:/run/containerd
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/machine-id:/etc/machine-id
      - /var/log:/var/log # To be able to serve default containers logs through api
      - /tmp:/tmp # To be able to read temporary fifo log files
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - path: /etc/machine-id
    contents: "104CECBC-6037-5FCF-AF75-80EB7040CD11"
    mode: "0600"
trust:
  org:
    - linuxkit
